apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  id: https://runtimeconditions.io/conformance/conflict-first:1.0.0
  version: 1.0.0
spec:
  kinds:
    - name: shared
