apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  uri: https://runtimeconditions.io/conformance/conflict-first
  version: 1.0.0
spec:
  kinds:
    - name: shared
