apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  id: urn:runtimeconditions:conformance:conflict:root
  version: 1.0.0
spec:
  dependencies:
    - urn:runtimeconditions:conformance:conflict:first
    - urn:runtimeconditions:conformance:conflict:second
  kinds:
    - name: root
