apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  uri: https://runtimeconditions.io/conformance/conflict-root
  version: 1.0.0
spec:
  dependencies:
    - https://runtimeconditions.io/conformance/conflict-first:1.0.0
    - https://runtimeconditions.io/conformance/conflict-second:1.0.0
  kinds:
    - name: root
