apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  id: https://runtimeconditions.io/conformance/unsupported-structural-keyword:1.0.0
  version: 1.0.0
spec:
  kinds:
    - name: tuple
  schemas:
    - id: tuple-values
      description: Unsupported tuple structure.
      appliesToKind: tuple
      schema:
        type: object
        properties:
          values:
            type: array
            prefixItems:
              - type: string
              - type: integer
        additionalProperties: false
