apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  uri: https://runtimeconditions.io/conformance/heterogeneous-union
  version: 1.0.0
spec:
  kinds:
    - name: selector
  interfaceTypes:
    - name: target
      targetKind: selector
  schemas:
    - id: heterogeneous-target
      description: Heterogeneous target union.
      appliesToKind: selector
      appliesToInterfaceType: target
      schema:
        type: object
        required: [kind, interface]
        properties:
          kind:
            const: selector
          interface:
            type: object
            required: [type]
            properties:
              type:
                const: target
            additionalProperties: false
          target:
            oneOf:
              - type: string
              - type: object
                required: [id]
                properties:
                  id:
                    type: string
                additionalProperties: false
        additionalProperties: false
