apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  uri: https://runtimeconditions.io/conformance/cycle-dependency
  version: 1.0.0
spec:
  dependencies:
    - https://runtimeconditions.io/conformance/cycle-root:1.0.0
  kinds:
    - name: dependency
