apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsBinding

metadata:
  extension: https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml
  extensionDefinition: ../env-configuration-v1alpha1.yaml
  language: java

java:
  package: io.runtimeconditions.extensions.envconfiguration

  options:
    - class: EnvConfiguration
      function: env
      target: configuration.env[]
      appliesToKinds: &condition_kinds
        - api
        - datastore
        - cache
      appliesToInterfaceTypes: &condition_interface_types
        - http
        - relational
        - document
        - key_value
      stringArgs: &env_string_args
        property: 0
        name: 1
      options: &env_input_options
        - class: EnvConfiguration
          function: sensitive
          target: env.sensitive
          value: "true"
        - class: EnvConfiguration
          function: optional
          target: env.required
          value: "false"

    - class: EnvConfiguration
      function: envAlternative
      target: configuration.alternatives[]
      appliesToKinds: *condition_kinds
      appliesToInterfaceTypes: *condition_interface_types
      options:
        - class: EnvConfiguration
          function: env
          target: configuration.env[]
          stringArgs: *env_string_args
          options: *env_input_options
