apiVersion: runtimeconditions.io/service-operations-semantic-bridge/v1alpha1
kind: RuntimeConditionsServiceOperationsSemanticBridge
metadata:
  name: kubernetes.api
  service: kubernetes-api
operationSource:
  kind: OpenAPIDocument
  repository: https://github.com/kubernetes/kubernetes.git
  revision: 24e2b02af5543d7910c2bb074c7264df5a8f0467
  ref: v1.36.2
  path: api/openapi-spec/swagger.json
  sha256: dcede2063da1d7ad62ecb5af8adb6d7fabd0b52385a7fa0048afb491dac90450
  semanticSha256: ca58855c8fe1774f8859e957ec94ebb41b016ea726e986f166460eefce488cfd
  operationCount: 1123
  operationIdsSha256: f32fcf3c6d90729c067ef7df8b7ece4e9c9cc52a7a29958d1df6519e0471e15d
extension:
  id: https://runtimeconditions.io/extensions/kubernetes-api/0.1.0/runtimeconditions.extension.yaml
  version: 0.1.0
  conditionKind: kubernetes
  interfaceType: api
resourceOperations:
  actionMappings:
    connect: connect
    create: create
    delete: delete
    deletecollection: deletecollection
    get: get
    list: list
    patch: patch
    post: create
    put: update
    update: update
    watch: watch
    watchlist: watch
  scopes:
    clusterRouteForNamespacedResource: all_namespaces
    clusterRoute: cluster
    namespacedRoute: namespaced
  connectRequiresHttpMethod: true
nonResourceOperations:
  httpMethods:
  - delete
  - get
  - head
  - options
  - patch
  - post
  - put
  - trace
