apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  uri: https://runtimeconditions.io/conformance/transitive-middle
  version: 1.0.0
spec:
  dependencies:
    - https://runtimeconditions.io/conformance/transitive-leaf:1.0.0
  interfaceTypes:
    - name: process
      targetKind: worker
