apiVersion: runtimeconditions.io/v1alpha1
kind: RuntimeConditionsExtensionDefinition
metadata:
  id: https://runtimeconditions.io/conformance/transitive-root:1.0.0
  version: 1.0.0
spec:
  dependencies:
    - https://runtimeconditions.io/conformance/transitive-middle:1.0.0
  conditionFields:
    - name: command
      appliesToKinds: [worker]
      appliesToInterfaceTypes: [process]
  schemas:
    - id: worker-process
      description: Worker process structure.
      appliesToKind: worker
      appliesToInterfaceType: process
      schema:
        type: object
        properties:
          command:
            type: string
        additionalProperties: true
