// Code generated by rc-go-bindings 0.1.0. DO NOT EDIT.
// Binding model SHA-256: a12e2b48fa7d88471af4d1e30da55ff290f0868294f9de6f9ffad5d7d3c738e6

package commonintegrations

// Declaration is the inert result of a Runtime Conditions declaration.
type Declaration struct{}

// ApiField is the field contract for Api declarations.
type ApiField interface {
	RuntimeConditionsApiField3bfbc0d376d30c4ae7aeaded7d946ac207023093793141f933c33ef9ff9eece6()
}

// Api declares a api Condition.
func Api(fields ...ApiField) Declaration { return Declaration{} }

// CacheField is the field contract for Cache declarations.
type CacheField interface {
	RuntimeConditionsCacheFieldc7214f8c564848866bebf298249c170ca9828a45dbac86e43be30fda1f9cd33c()
}

// Cache declares a cache Condition.
func Cache(fields ...CacheField) Declaration { return Declaration{} }

// DatastoreField is the field contract for Datastore declarations.
type DatastoreField interface {
	RuntimeConditionsDatastoreFieldb7ebbd32300fa1c90e7441751436af0b21a62c1c126b31db4ca4cda47ba2eb26()
}

// Datastore declares a datastore Condition.
func Datastore(fields ...DatastoreField) Declaration { return Declaration{} }

// Document is generated from interface:datastore:document.
type Document struct {
	Engine *DocumentEngine
}

func (Document) RuntimeConditionsDatastoreFieldb7ebbd32300fa1c90e7441751436af0b21a62c1c126b31db4ca4cda47ba2eb26() {
}

// DocumentEngine is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:datastore-document-interface/properties/interface/properties/engine.
type DocumentEngine string

// Format is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/properties/interface/properties/spec/properties/format.
type Format string

// Http is generated from interface:api:http.
type Http struct {
	Operations Operations
	Spec       *Spec
}

func (Http) RuntimeConditionsApiField3bfbc0d376d30c4ae7aeaded7d946ac207023093793141f933c33ef9ff9eece6() {
}

// KeyValue is generated from interface:cache:key_value.
type KeyValue struct {
	Engine *KeyValueEngine
}

func (KeyValue) RuntimeConditionsCacheFieldc7214f8c564848866bebf298249c170ca9828a45dbac86e43be30fda1f9cd33c() {
}

// KeyValueEngine is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:cache-key-value-interface/properties/interface/properties/engine.
type KeyValueEngine string

// Method is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/properties/interface/properties/operations/items/properties/method.
type Method string

// Operations is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/properties/interface/properties/operations.
type Operations []OperationsItem

// OperationsItem is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/properties/interface/properties/operations/items.
type OperationsItem struct {
	Method            Method
	Path              string
	RequestBodySchema RequestBodySchema
	ResponseSchema    ResponseSchema
}

// Relational is generated from interface:datastore:relational.
type Relational struct {
	Engine *RelationalEngine
}

func (Relational) RuntimeConditionsDatastoreFieldb7ebbd32300fa1c90e7441751436af0b21a62c1c126b31db4ca4cda47ba2eb26() {
}

// RelationalEngine is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:datastore-relational-interface/properties/interface/properties/engine.
type RelationalEngine string

// RequestBodySchema is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema.
type RequestBodySchema interface {
	runtimeConditionsRequestBodySchema()
}

// RequestBodySchemaArray is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/2.
type RequestBodySchemaArray []SimpleSchema

func (RequestBodySchemaArray) runtimeConditionsRequestBodySchema() {}

// RequestBodySchemaMap is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/0.
type RequestBodySchemaMap map[string]SimpleSchema

func (RequestBodySchemaMap) runtimeConditionsRequestBodySchema() {}

// RequestBodySchemaString is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/1.
type RequestBodySchemaString string

func (RequestBodySchemaString) runtimeConditionsRequestBodySchema() {}

// ResponseSchema is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema.
type ResponseSchema interface {
	runtimeConditionsResponseSchema()
}

// ResponseSchemaArray is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/2.
type ResponseSchemaArray []SimpleSchema

func (ResponseSchemaArray) runtimeConditionsResponseSchema() {}

// ResponseSchemaMap is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/0.
type ResponseSchemaMap map[string]SimpleSchema

func (ResponseSchemaMap) runtimeConditionsResponseSchema() {}

// ResponseSchemaString is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/1.
type ResponseSchemaString string

func (ResponseSchemaString) runtimeConditionsResponseSchema() {}

// SimpleSchema is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema.
type SimpleSchema interface {
	runtimeConditionsSimpleSchema()
}

// SimpleSchemaArray is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/2.
type SimpleSchemaArray []SimpleSchema

func (SimpleSchemaArray) runtimeConditionsSimpleSchema() {}

// SimpleSchemaMap is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/0.
type SimpleSchemaMap map[string]SimpleSchema

func (SimpleSchemaMap) runtimeConditionsSimpleSchema() {}

// SimpleSchemaString is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/$defs/simpleSchema/oneOf/1.
type SimpleSchemaString string

func (SimpleSchemaString) runtimeConditionsSimpleSchema() {}

// Spec is generated from https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml#schema:api-http-interface/properties/interface/properties/spec.
type Spec struct {
	Format  Format
	Uri     string
	Version *string
}

const (
	DocumentEngineCouchbase        DocumentEngine          = "couchbase"
	DocumentEngineMongodb          DocumentEngine          = "mongodb"
	FormatOpenapi                  Format                  = "openapi"
	KeyValueEngineMemcached        KeyValueEngine          = "memcached"
	KeyValueEngineRedis            KeyValueEngine          = "redis"
	MethodDelete                   Method                  = "DELETE"
	MethodGet                      Method                  = "GET"
	MethodHead                     Method                  = "HEAD"
	MethodOptions                  Method                  = "OPTIONS"
	MethodPatch                    Method                  = "PATCH"
	MethodPost                     Method                  = "POST"
	MethodPut                      Method                  = "PUT"
	MethodTrace                    Method                  = "TRACE"
	RelationalEngineMariadb        RelationalEngine        = "mariadb"
	RelationalEngineMysql          RelationalEngine        = "mysql"
	RelationalEngineOracle         RelationalEngine        = "oracle"
	RelationalEnginePostgres       RelationalEngine        = "postgres"
	RelationalEngineSqlite         RelationalEngine        = "sqlite"
	RelationalEngineSqlserver      RelationalEngine        = "sqlserver"
	RequestBodySchemaStringBoolean RequestBodySchemaString = "boolean"
	RequestBodySchemaStringInteger RequestBodySchemaString = "integer"
	RequestBodySchemaStringNull    RequestBodySchemaString = "null"
	RequestBodySchemaStringNumber  RequestBodySchemaString = "number"
	RequestBodySchemaStringString  RequestBodySchemaString = "string"
	ResponseSchemaStringBoolean    ResponseSchemaString    = "boolean"
	ResponseSchemaStringInteger    ResponseSchemaString    = "integer"
	ResponseSchemaStringNull       ResponseSchemaString    = "null"
	ResponseSchemaStringNumber     ResponseSchemaString    = "number"
	ResponseSchemaStringString     ResponseSchemaString    = "string"
	SimpleSchemaStringBoolean      SimpleSchemaString      = "boolean"
	SimpleSchemaStringInteger      SimpleSchemaString      = "integer"
	SimpleSchemaStringNull         SimpleSchemaString      = "null"
	SimpleSchemaStringNumber       SimpleSchemaString      = "number"
	SimpleSchemaStringString       SimpleSchemaString      = "string"
)
