// Code generated by rc-go-bindings 0.1.0. DO NOT EDIT.
// Binding model SHA-256: fe7747e31ec05f7282de377fc3e2c2bd89f7949048b1d0cefe557307a1f22a66

module github.com/runtimeconditions/extensions/bindings/common-integrations/go

go 1.25
