apiVersion: runtimeconditions.io/binding-release/v1alpha1
dependencyLock:
    extensions:
        - id: https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml
          version: v1alpha1
          sourceSha256: ef0d9e71d0d5d481c367002cecd2d3eef15475a40493f231521d778492a216ed
          semanticSha256: 0952ff5e52486a87e64808a09e8aa28d124a00efdeb9e174c4153d644879d54c
          sourceBackend: catalog
          sourceLocator: catalog:rc/common-integrations/common-integrations-v1alpha1.yaml
kind: RuntimeConditionsBindingRelease
model:
    apiVersion: runtimeconditions.io/binding-model/v1alpha1
    semanticSha256: d17e868261cd8080095f600634204748ae936ae42870eb7b6d30318ede26f523
package:
    coordinate: runtimeconditions.io/x/rc/common
    language: go
    minimumGoVersion: "1.25"
    name: common
    packageKey: common-integrations
    publicationMode: github-tag
    version: v0.1.0
packageDependencies: []
provenance:
    mode: production
    orchestrator:
        name: rc
        version: 0.1.0
        sha256: 6cdffc1ee75a3112edadc9ff61c77d5489844791853f8ad7d9cb88f459d8fbcf
    profiler:
        name: go-rc-profiler
        version: v0.4.0
        sha256: 1a2f761c63a26a75417f5fa487be3504266856004b85fd68cccae80d3e176c60
    sourceDirectory: bindings/common-integrations/go
    targetReleaseTag: bindings/common-integrations/go/v0.1.0
rootExtension:
    id: https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml
    version: v1alpha1
    semanticSha256: 0952ff5e52486a87e64808a09e8aa28d124a00efdeb9e174c4153d644879d54c
