// Code generated by rc-go-bindings 0.1.0. DO NOT EDIT.
// Binding model SHA-256: aeb7e5f0efa2b481d4b88e06d18567de8015c70e8be33bde9c05c9c22f6c1a05

package env

// Declaration is the inert result of a Runtime Conditions declaration.
type Declaration struct{}

// DocumentConfiguration is generated from condition-field:datastore:document:configuration.
type DocumentConfiguration struct {
	Alternatives DocumentConfigurationAlternatives
	Env          DocumentConfigurationEnv
}

func (DocumentConfiguration) RuntimeConditionsDatastoreFieldb7ebbd32300fa1c90e7441751436af0b21a62c1c126b31db4ca4cda47ba2eb26() {
}

// DocumentConfigurationAlternatives is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/configuration/properties/alternatives.
type DocumentConfigurationAlternatives []DocumentConfigurationAlternativesItem

// DocumentConfigurationAlternativesEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/configuration/properties/alternatives/items/properties/env.
type DocumentConfigurationAlternativesEnv []DocumentConfigurationAlternativesEnvItem

// DocumentConfigurationAlternativesEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/envInput.
type DocumentConfigurationAlternativesEnvItem struct {
	Name      string
	Property  DocumentConfigurationAlternativesEnvProperty
	Required  *bool
	Sensitive *bool
}

// DocumentConfigurationAlternativesEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/allowedProperty.
type DocumentConfigurationAlternativesEnvProperty string

// DocumentConfigurationAlternativesItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/configuration/properties/alternatives/items.
type DocumentConfigurationAlternativesItem struct {
	Env DocumentConfigurationAlternativesEnv
}

// DocumentConfigurationEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/configuration/properties/env.
type DocumentConfigurationEnv []DocumentConfigurationEnvItem

// DocumentConfigurationEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/envInput.
type DocumentConfigurationEnvItem struct {
	Name      string
	Property  DocumentConfigurationEnvProperty
	Required  *bool
	Sensitive *bool
}

// DocumentConfigurationEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-document/$defs/allowedProperty.
type DocumentConfigurationEnvProperty string

// HttpConfiguration is generated from condition-field:api:http:configuration.
type HttpConfiguration struct {
	Alternatives HttpConfigurationAlternatives
	Env          HttpConfigurationEnv
}

func (HttpConfiguration) RuntimeConditionsApiField3bfbc0d376d30c4ae7aeaded7d946ac207023093793141f933c33ef9ff9eece6() {
}

// HttpConfigurationAlternatives is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/configuration/properties/alternatives.
type HttpConfigurationAlternatives []HttpConfigurationAlternativesItem

// HttpConfigurationAlternativesEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/configuration/properties/alternatives/items/properties/env.
type HttpConfigurationAlternativesEnv []HttpConfigurationAlternativesEnvItem

// HttpConfigurationAlternativesEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/envInput.
type HttpConfigurationAlternativesEnvItem struct {
	Name      string
	Property  HttpConfigurationAlternativesEnvProperty
	Required  *bool
	Sensitive *bool
}

// HttpConfigurationAlternativesEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/allowedProperty.
type HttpConfigurationAlternativesEnvProperty string

// HttpConfigurationAlternativesItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/configuration/properties/alternatives/items.
type HttpConfigurationAlternativesItem struct {
	Env HttpConfigurationAlternativesEnv
}

// HttpConfigurationEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/configuration/properties/env.
type HttpConfigurationEnv []HttpConfigurationEnvItem

// HttpConfigurationEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/envInput.
type HttpConfigurationEnvItem struct {
	Name      string
	Property  HttpConfigurationEnvProperty
	Required  *bool
	Sensitive *bool
}

// HttpConfigurationEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-api-http/$defs/allowedProperty.
type HttpConfigurationEnvProperty string

// KeyValueConfiguration is generated from condition-field:cache:key_value:configuration.
type KeyValueConfiguration struct {
	Alternatives KeyValueConfigurationAlternatives
	Env          KeyValueConfigurationEnv
}

func (KeyValueConfiguration) RuntimeConditionsCacheFieldc7214f8c564848866bebf298249c170ca9828a45dbac86e43be30fda1f9cd33c() {
}

// KeyValueConfigurationAlternatives is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/configuration/properties/alternatives.
type KeyValueConfigurationAlternatives []KeyValueConfigurationAlternativesItem

// KeyValueConfigurationAlternativesEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/configuration/properties/alternatives/items/properties/env.
type KeyValueConfigurationAlternativesEnv []KeyValueConfigurationAlternativesEnvItem

// KeyValueConfigurationAlternativesEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/envInput.
type KeyValueConfigurationAlternativesEnvItem struct {
	Name      string
	Property  KeyValueConfigurationAlternativesEnvProperty
	Required  *bool
	Sensitive *bool
}

// KeyValueConfigurationAlternativesEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/allowedProperty.
type KeyValueConfigurationAlternativesEnvProperty string

// KeyValueConfigurationAlternativesItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/configuration/properties/alternatives/items.
type KeyValueConfigurationAlternativesItem struct {
	Env KeyValueConfigurationAlternativesEnv
}

// KeyValueConfigurationEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/configuration/properties/env.
type KeyValueConfigurationEnv []KeyValueConfigurationEnvItem

// KeyValueConfigurationEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/envInput.
type KeyValueConfigurationEnvItem struct {
	Name      string
	Property  KeyValueConfigurationEnvProperty
	Required  *bool
	Sensitive *bool
}

// KeyValueConfigurationEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-cache-key-value/$defs/allowedProperty.
type KeyValueConfigurationEnvProperty string

// RelationalConfiguration is generated from condition-field:datastore:relational:configuration.
type RelationalConfiguration struct {
	Alternatives RelationalConfigurationAlternatives
	Env          RelationalConfigurationEnv
}

func (RelationalConfiguration) RuntimeConditionsDatastoreFieldb7ebbd32300fa1c90e7441751436af0b21a62c1c126b31db4ca4cda47ba2eb26() {
}

// RelationalConfigurationAlternatives is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/configuration/properties/alternatives.
type RelationalConfigurationAlternatives []RelationalConfigurationAlternativesItem

// RelationalConfigurationAlternativesEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/configuration/properties/alternatives/items/properties/env.
type RelationalConfigurationAlternativesEnv []RelationalConfigurationAlternativesEnvItem

// RelationalConfigurationAlternativesEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/envInput.
type RelationalConfigurationAlternativesEnvItem struct {
	Name      string
	Property  RelationalConfigurationAlternativesEnvProperty
	Required  *bool
	Sensitive *bool
}

// RelationalConfigurationAlternativesEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/allowedProperty.
type RelationalConfigurationAlternativesEnvProperty string

// RelationalConfigurationAlternativesItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/configuration/properties/alternatives/items.
type RelationalConfigurationAlternativesItem struct {
	Env RelationalConfigurationAlternativesEnv
}

// RelationalConfigurationEnv is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/configuration/properties/env.
type RelationalConfigurationEnv []RelationalConfigurationEnvItem

// RelationalConfigurationEnvItem is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/envInput.
type RelationalConfigurationEnvItem struct {
	Name      string
	Property  RelationalConfigurationEnvProperty
	Required  *bool
	Sensitive *bool
}

// RelationalConfigurationEnvProperty is generated from https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml#schema:configuration-properties-datastore-relational/$defs/allowedProperty.
type RelationalConfigurationEnvProperty string

const (
	DocumentConfigurationAlternativesEnvPropertyDatabase   DocumentConfigurationAlternativesEnvProperty   = "database"
	DocumentConfigurationAlternativesEnvPropertyHostname   DocumentConfigurationAlternativesEnvProperty   = "hostname"
	DocumentConfigurationAlternativesEnvPropertyPassword   DocumentConfigurationAlternativesEnvProperty   = "password"
	DocumentConfigurationAlternativesEnvPropertyPort       DocumentConfigurationAlternativesEnvProperty   = "port"
	DocumentConfigurationAlternativesEnvPropertyScheme     DocumentConfigurationAlternativesEnvProperty   = "scheme"
	DocumentConfigurationAlternativesEnvPropertyTls        DocumentConfigurationAlternativesEnvProperty   = "tls"
	DocumentConfigurationAlternativesEnvPropertyUrl        DocumentConfigurationAlternativesEnvProperty   = "url"
	DocumentConfigurationAlternativesEnvPropertyUsername   DocumentConfigurationAlternativesEnvProperty   = "username"
	DocumentConfigurationEnvPropertyDatabase               DocumentConfigurationEnvProperty               = "database"
	DocumentConfigurationEnvPropertyHostname               DocumentConfigurationEnvProperty               = "hostname"
	DocumentConfigurationEnvPropertyPassword               DocumentConfigurationEnvProperty               = "password"
	DocumentConfigurationEnvPropertyPort                   DocumentConfigurationEnvProperty               = "port"
	DocumentConfigurationEnvPropertyScheme                 DocumentConfigurationEnvProperty               = "scheme"
	DocumentConfigurationEnvPropertyTls                    DocumentConfigurationEnvProperty               = "tls"
	DocumentConfigurationEnvPropertyUrl                    DocumentConfigurationEnvProperty               = "url"
	DocumentConfigurationEnvPropertyUsername               DocumentConfigurationEnvProperty               = "username"
	HttpConfigurationAlternativesEnvPropertyBaseUrl        HttpConfigurationAlternativesEnvProperty       = "baseUrl"
	HttpConfigurationAlternativesEnvPropertyHostname       HttpConfigurationAlternativesEnvProperty       = "hostname"
	HttpConfigurationAlternativesEnvPropertyPassword       HttpConfigurationAlternativesEnvProperty       = "password"
	HttpConfigurationAlternativesEnvPropertyPort           HttpConfigurationAlternativesEnvProperty       = "port"
	HttpConfigurationAlternativesEnvPropertyScheme         HttpConfigurationAlternativesEnvProperty       = "scheme"
	HttpConfigurationAlternativesEnvPropertyTls            HttpConfigurationAlternativesEnvProperty       = "tls"
	HttpConfigurationAlternativesEnvPropertyToken          HttpConfigurationAlternativesEnvProperty       = "token"
	HttpConfigurationAlternativesEnvPropertyUrl            HttpConfigurationAlternativesEnvProperty       = "url"
	HttpConfigurationAlternativesEnvPropertyUsername       HttpConfigurationAlternativesEnvProperty       = "username"
	HttpConfigurationEnvPropertyBaseUrl                    HttpConfigurationEnvProperty                   = "baseUrl"
	HttpConfigurationEnvPropertyHostname                   HttpConfigurationEnvProperty                   = "hostname"
	HttpConfigurationEnvPropertyPassword                   HttpConfigurationEnvProperty                   = "password"
	HttpConfigurationEnvPropertyPort                       HttpConfigurationEnvProperty                   = "port"
	HttpConfigurationEnvPropertyScheme                     HttpConfigurationEnvProperty                   = "scheme"
	HttpConfigurationEnvPropertyTls                        HttpConfigurationEnvProperty                   = "tls"
	HttpConfigurationEnvPropertyToken                      HttpConfigurationEnvProperty                   = "token"
	HttpConfigurationEnvPropertyUrl                        HttpConfigurationEnvProperty                   = "url"
	HttpConfigurationEnvPropertyUsername                   HttpConfigurationEnvProperty                   = "username"
	KeyValueConfigurationAlternativesEnvPropertyDatabase   KeyValueConfigurationAlternativesEnvProperty   = "database"
	KeyValueConfigurationAlternativesEnvPropertyHostname   KeyValueConfigurationAlternativesEnvProperty   = "hostname"
	KeyValueConfigurationAlternativesEnvPropertyPassword   KeyValueConfigurationAlternativesEnvProperty   = "password"
	KeyValueConfigurationAlternativesEnvPropertyPort       KeyValueConfigurationAlternativesEnvProperty   = "port"
	KeyValueConfigurationAlternativesEnvPropertyScheme     KeyValueConfigurationAlternativesEnvProperty   = "scheme"
	KeyValueConfigurationAlternativesEnvPropertyTls        KeyValueConfigurationAlternativesEnvProperty   = "tls"
	KeyValueConfigurationAlternativesEnvPropertyToken      KeyValueConfigurationAlternativesEnvProperty   = "token"
	KeyValueConfigurationAlternativesEnvPropertyUrl        KeyValueConfigurationAlternativesEnvProperty   = "url"
	KeyValueConfigurationAlternativesEnvPropertyUsername   KeyValueConfigurationAlternativesEnvProperty   = "username"
	KeyValueConfigurationEnvPropertyDatabase               KeyValueConfigurationEnvProperty               = "database"
	KeyValueConfigurationEnvPropertyHostname               KeyValueConfigurationEnvProperty               = "hostname"
	KeyValueConfigurationEnvPropertyPassword               KeyValueConfigurationEnvProperty               = "password"
	KeyValueConfigurationEnvPropertyPort                   KeyValueConfigurationEnvProperty               = "port"
	KeyValueConfigurationEnvPropertyScheme                 KeyValueConfigurationEnvProperty               = "scheme"
	KeyValueConfigurationEnvPropertyTls                    KeyValueConfigurationEnvProperty               = "tls"
	KeyValueConfigurationEnvPropertyToken                  KeyValueConfigurationEnvProperty               = "token"
	KeyValueConfigurationEnvPropertyUrl                    KeyValueConfigurationEnvProperty               = "url"
	KeyValueConfigurationEnvPropertyUsername               KeyValueConfigurationEnvProperty               = "username"
	RelationalConfigurationAlternativesEnvPropertyDatabase RelationalConfigurationAlternativesEnvProperty = "database"
	RelationalConfigurationAlternativesEnvPropertyHostname RelationalConfigurationAlternativesEnvProperty = "hostname"
	RelationalConfigurationAlternativesEnvPropertyPassword RelationalConfigurationAlternativesEnvProperty = "password"
	RelationalConfigurationAlternativesEnvPropertyPort     RelationalConfigurationAlternativesEnvProperty = "port"
	RelationalConfigurationAlternativesEnvPropertyScheme   RelationalConfigurationAlternativesEnvProperty = "scheme"
	RelationalConfigurationAlternativesEnvPropertyTls      RelationalConfigurationAlternativesEnvProperty = "tls"
	RelationalConfigurationAlternativesEnvPropertyUrl      RelationalConfigurationAlternativesEnvProperty = "url"
	RelationalConfigurationAlternativesEnvPropertyUsername RelationalConfigurationAlternativesEnvProperty = "username"
	RelationalConfigurationEnvPropertyDatabase             RelationalConfigurationEnvProperty             = "database"
	RelationalConfigurationEnvPropertyHostname             RelationalConfigurationEnvProperty             = "hostname"
	RelationalConfigurationEnvPropertyPassword             RelationalConfigurationEnvProperty             = "password"
	RelationalConfigurationEnvPropertyPort                 RelationalConfigurationEnvProperty             = "port"
	RelationalConfigurationEnvPropertyScheme               RelationalConfigurationEnvProperty             = "scheme"
	RelationalConfigurationEnvPropertyTls                  RelationalConfigurationEnvProperty             = "tls"
	RelationalConfigurationEnvPropertyUrl                  RelationalConfigurationEnvProperty             = "url"
	RelationalConfigurationEnvPropertyUsername             RelationalConfigurationEnvProperty             = "username"
)
