// Code generated by rc-go-bindings 0.1.0. DO NOT EDIT.
// Binding model SHA-256: aeb7e5f0efa2b481d4b88e06d18567de8015c70e8be33bde9c05c9c22f6c1a05

module runtimeconditions.io/x/rc/env

go 1.25

require (
	runtimeconditions.io/x/rc/common v0.1.0
)
