// Code generated by rc-go-bindings 0.1.0. DO NOT EDIT.
// Binding model SHA-256: 8ea51cb5fb6a1234917bbcb7ba915aba59c73b6decc7656b62023937293e7231

module runtimeconditions.io/x/rc/env

go 1.25

require (
	runtimeconditions.io/x/rc/common v0.1.0
)
