// Code generated by rc-go-bindings 0.1.0. DO NOT EDIT.
// Binding model SHA-256: 01be94b2e94f29f205b6d81cf4a1b3eaf15b7111a029fde32faa600ca804899e

module github.com/runtimeconditions/extensions/bindings/env-configuration/go

go 1.25

require (
	github.com/runtimeconditions/extensions/bindings/common-integrations/go v0.1.0
)
