apiVersion: runtimeconditions.io/binding-release/v1alpha1
dependencyLock:
    extensions:
        - id: https://runtimeconditions.io/common-integrations:v1alpha1
          version: v1alpha1
          sourceSha256: 51c3ee571d69ad3d3690080d30f223ba1e8296c9e18aa4974fad367c6a01a2da
          semanticSha256: e2fe5d6a0ac52b19cbed8fd5e0bb4b35d01ec9bdff2877255a9cfba8136ab913
          sourceBackend: catalog
          sourceLocator: catalog:rc/common-integrations/common-integrations-v1alpha1.yaml
        - id: https://runtimeconditions.io/env-configuration:v1alpha1
          version: v1alpha1
          sourceSha256: 5ec63b5d4f0921b40b20da0c3dfcfc76c28a5b52cc15f072d1beded8791c08c7
          semanticSha256: 0453bc362c6a6dfe9b9d0bf878f7f50625aafab0ab3bf42037bef09cf6a9ca4a
          sourceBackend: catalog
          sourceLocator: catalog:rc/env-configuration/env-configuration-v1alpha1.yaml
          dependencies:
            - https://runtimeconditions.io/common-integrations:v1alpha1
kind: RuntimeConditionsBindingRelease
model:
    apiVersion: runtimeconditions.io/binding-model/v1alpha1
    semanticSha256: 01be94b2e94f29f205b6d81cf4a1b3eaf15b7111a029fde32faa600ca804899e
package:
    coordinate: github.com/runtimeconditions/extensions/bindings/env-configuration/go
    language: go
    minimumGoVersion: "1.25"
    name: envconfiguration
    packageKey: env-configuration
    publicationMode: github-tag
    version: v0.1.0
packageDependencies:
    - artifact:
        kind: go-module-zip
        sha256: cb47ac83d5476a10901056ad1149c36c31f64cc13c9bc25f49a1fb97f5303d83
      compatibleVersionRange:
        minimumInclusive: v0.1.0
        nextBreakingExclusive: v0.2.0
      coordinate: github.com/runtimeconditions/extensions/bindings/common-integrations/go
      extension: https://runtimeconditions.io/common-integrations:v1alpha1
      name: commonintegrations
      testedVersion: v0.1.0
provenance:
    mode: production
    orchestrator:
        name: rc
        version: 0.1.0
        sha256: 44185e78ea5931ca244954f09c239107991d6d13b9f9f7162eac62eef52a2156
    profiler:
        name: go-rc-profiler
        version: v0.0.3
        sha256: a8b055076876f4a77667f0674caaadf473db7a43fe00745a3dff3aaa29f03f6e
    sourceDirectory: bindings/env-configuration/go
    targetReleaseTag: bindings/env-configuration/go/v0.1.0
rootExtension:
    id: https://runtimeconditions.io/env-configuration:v1alpha1
    version: v1alpha1
    semanticSha256: 0453bc362c6a6dfe9b9d0bf878f7f50625aafab0ab3bf42037bef09cf6a9ca4a
