apiVersion: runtimeconditions.io/binding-release/v1alpha1
dependencyLock:
    extensions:
        - id: https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml
          version: v1alpha1
          sourceSha256: ef0d9e71d0d5d481c367002cecd2d3eef15475a40493f231521d778492a216ed
          semanticSha256: 0952ff5e52486a87e64808a09e8aa28d124a00efdeb9e174c4153d644879d54c
          sourceBackend: catalog
          sourceLocator: catalog:rc/common-integrations/common-integrations-v1alpha1.yaml
        - id: https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml
          version: v1alpha1
          sourceSha256: 645e5de82fcfc22c1e3b3bf06534c0cf13baed12b4994548a1f9a9be53a9e7f4
          semanticSha256: c6bd5fec1cc31b2b828cb97da2f56773862a70ef04e94dac7652f87a0af7435b
          sourceBackend: catalog
          sourceLocator: catalog:rc/env-configuration/env-configuration-v1alpha1.yaml
          dependencies:
            - https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml
kind: RuntimeConditionsBindingRelease
model:
    apiVersion: runtimeconditions.io/binding-model/v1alpha1
    semanticSha256: aeb7e5f0efa2b481d4b88e06d18567de8015c70e8be33bde9c05c9c22f6c1a05
package:
    coordinate: runtimeconditions.io/x/rc/env
    language: go
    minimumGoVersion: "1.25"
    name: env
    packageKey: env-configuration
    publicationMode: github-tag
    version: v0.1.0
packageDependencies:
    - artifact:
        kind: go-module-zip
        sha256: cc875f443c3fe9a3d34111ff98beb85338fec28db7fa5ddc48af687d567bc0ce
      compatibleVersionRange:
        minimumInclusive: v0.1.0
        nextBreakingExclusive: v0.2.0
      coordinate: runtimeconditions.io/x/rc/common
      extension: https://runtimeconditions.io/extensions/common-integrations/v1alpha1/runtimeconditions.extension.yaml
      name: common
      testedVersion: v0.1.0
provenance:
    mode: production
    orchestrator:
        name: rc
        version: 0.1.0
        sha256: 6cdffc1ee75a3112edadc9ff61c77d5489844791853f8ad7d9cb88f459d8fbcf
    profiler:
        name: go-rc-profiler
        version: v0.4.0
        sha256: 1a2f761c63a26a75417f5fa487be3504266856004b85fd68cccae80d3e176c60
    sourceDirectory: bindings/env-configuration/go
    targetReleaseTag: bindings/env-configuration/go/v0.1.0
rootExtension:
    id: https://runtimeconditions.io/extensions/env-configuration/v1alpha1/runtimeconditions.extension.yaml
    version: v1alpha1
    semanticSha256: c6bd5fec1cc31b2b828cb97da2f56773862a70ef04e94dac7652f87a0af7435b
