"""Build and verify deterministic Python binding package archives."""

from __future__ import annotations

import base64
import csv
import gzip
import io
import json
import os
import shutil
import stat
import subprocess
import tarfile
import zipfile
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from .emitter import EmissionPlan
from .metadata import _version
from .package import fail
from .source import (
    render_assembly_metadata,
    render_package,
)

ARCHIVE_EPOCH = 315532800  # 1980-01-01 UTC, the earliest ZIP timestamp.
_BUILD_TOOLS = ("pip", "setuptools", "build", "wheel", "packaging", "pyproject_hooks")


@dataclass(frozen=True)
class ArchiveArtifacts:
    wheel: Path
    sdist: Path


def _artifact_names(plan: EmissionPlan) -> tuple[str, str, str]:
    stem = plan.target.distribution_name.replace("-", "_")
    version = _version(plan.target.version, plan.target.package_key)
    return (
        f"{stem}-{version}-py3-none-any.whl",
        f"{stem}-{version}.tar.gz",
        f"{stem}-{version}",
    )


def _expected_wheel(
    plan: EmissionPlan,
    model: dict[str, Any],
    source_files: dict[str, str] | None = None,
) -> dict[str, bytes | None]:
    _, _, root = _artifact_names(plan)
    dist_info = f"{root}.dist-info"
    files: dict[str, bytes | None] = {
        path.removeprefix("src/"): content.encode("utf-8")
        for path, content in (
            source_files if source_files is not None else render_package(plan, model)
        ).items()
        if path.startswith("src/")
    }
    for name in ("METADATA", "WHEEL", "top_level.txt", "RECORD"):
        files[f"{dist_info}/{name}"] = None
    return files


def _expected_sdist(
    plan: EmissionPlan,
    model: dict[str, Any],
    source_files: dict[str, str] | None = None,
) -> dict[str, bytes | None]:
    _, _, root = _artifact_names(plan)
    stem = plan.target.distribution_name.replace("-", "_")
    files: dict[str, bytes | None] = {
        f"{root}/{path}": content.encode("utf-8")
        for path, content in (
            source_files if source_files is not None else render_package(plan, model)
        ).items()
    }
    files[f"{root}/PKG-INFO"] = None
    files[f"{root}/setup.cfg"] = None  # Generated by the pinned setuptools backend.
    egg_info = f"{root}/src/{stem}.egg-info"
    for name in ("PKG-INFO", "SOURCES.txt", "dependency_links.txt", "top_level.txt"):
        files[f"{egg_info}/{name}"] = None
    if plan.target.dependencies:
        files[f"{egg_info}/requires.txt"] = None
    return files


def _check_names(actual: set[str], expected: set[str], coordinate: str) -> None:
    extra = sorted(actual - expected)
    missing = sorted(expected - actual)
    if extra or missing:
        fail(
            "archive",
            "RCP4004",
            coordinate,
            f"archive file set differs: extra={extra!r}, missing={missing!r}",
        )


def _check_expected_bytes(
    actual: dict[str, bytes], expected: dict[str, bytes | None], coordinate: str
) -> None:
    for name, content in expected.items():
        if content is not None and actual[name] != content:
            fail(
                "archive",
                "RCP4004",
                coordinate,
                f"archive file differs from generated source: {name!r}",
            )


def _check_record(files: dict[str, bytes], coordinate: str) -> None:
    record_name = next(name for name in files if name.endswith(".dist-info/RECORD"))
    try:
        rows = list(csv.reader(io.StringIO(files[record_name].decode("utf-8"))))
    except (UnicodeError, csv.Error):
        fail("archive", "RCP4004", coordinate, "wheel RECORD is malformed")
    listed: set[str] = set()
    for row in rows:
        if len(row) != 3 or row[0] in listed or row[0] not in files:
            fail("archive", "RCP4004", coordinate, "wheel RECORD has invalid entries")
        name, digest, size = row
        listed.add(name)
        if name == record_name:
            if digest or size:
                fail("archive", "RCP4004", coordinate, "wheel RECORD hashes itself")
            continue
        expected_digest = (
            base64.urlsafe_b64encode(sha256(files[name]).digest())
            .rstrip(b"=")
            .decode("ascii")
        )
        if digest != f"sha256={expected_digest}" or size != str(len(files[name])):
            fail(
                "archive",
                "RCP4004",
                coordinate,
                f"wheel RECORD hash or size differs: {name!r}",
            )
    _check_names(listed, set(files), coordinate)


def verify_wheel(
    path: str | Path,
    plan: EmissionPlan,
    model: dict[str, Any],
    source_files: dict[str, str] | None = None,
) -> None:
    """Reject undeclared or altered wheel entries, including RECORD mismatches."""
    coordinate = plan.target.package_key
    expected = _expected_wheel(plan, model, source_files)
    if Path(path).name != _artifact_names(plan)[0]:
        fail(
            "archive",
            "RCP4004",
            coordinate,
            "wheel filename differs from package metadata",
        )
    try:
        with zipfile.ZipFile(path) as archive:
            entries = archive.infolist()
            names = [entry.filename for entry in entries]
            if len(names) != len(set(names)):
                fail("archive", "RCP4004", coordinate, "wheel has duplicate entries")
            files: dict[str, bytes] = {}
            for entry in entries:
                file_type = stat.S_IFMT(entry.external_attr >> 16)
                if entry.is_dir() or file_type not in {0, stat.S_IFREG}:
                    fail("archive", "RCP4004", coordinate, "wheel has a non-file entry")
                files[entry.filename] = archive.read(entry)
    except (OSError, zipfile.BadZipFile, RuntimeError, ValueError):
        fail("archive", "RCP4004", coordinate, "wheel archive cannot be read")
    _check_names(set(files), set(expected), coordinate)
    _check_expected_bytes(files, expected, coordinate)
    _check_record(files, coordinate)


def verify_sdist(
    path: str | Path,
    plan: EmissionPlan,
    model: dict[str, Any],
    source_files: dict[str, str] | None = None,
) -> None:
    """Reject undeclared, missing, or altered source-distribution entries."""
    coordinate = plan.target.package_key
    expected = _expected_sdist(plan, model, source_files)
    if Path(path).name != _artifact_names(plan)[1]:
        fail(
            "archive",
            "RCP4004",
            coordinate,
            "sdist filename differs from package metadata",
        )
    try:
        with tarfile.open(path, "r:gz") as archive:
            members = archive.getmembers()
            names = [member.name for member in members]
            if len(names) != len(set(names)):
                fail("archive", "RCP4004", coordinate, "sdist has duplicate entries")
            files: dict[str, bytes] = {}
            for member in members:
                if member.isdir():
                    if not any(
                        name.startswith(member.name.rstrip("/") + "/")
                        for name in expected
                    ):
                        fail(
                            "archive",
                            "RCP4004",
                            coordinate,
                            "sdist has an undeclared directory",
                        )
                elif member.isfile():
                    stream = archive.extractfile(member)
                    if stream is None:
                        fail(
                            "archive",
                            "RCP4004",
                            coordinate,
                            "sdist file cannot be read",
                        )
                    files[member.name] = stream.read()
                else:
                    fail("archive", "RCP4004", coordinate, "sdist has a non-file entry")
    except (OSError, tarfile.TarError, EOFError, ValueError):
        fail("archive", "RCP4004", coordinate, "sdist archive cannot be read")
    _check_names(set(files), set(expected), coordinate)
    _check_expected_bytes(files, expected, coordinate)
    _, _, root = _artifact_names(plan)
    sources_name = next(
        name for name in files if name.endswith(".egg-info/SOURCES.txt")
    )
    try:
        listed = files[sources_name].decode("utf-8").splitlines()
    except UnicodeError:
        fail("archive", "RCP4004", coordinate, "sdist SOURCES.txt is malformed")
    declared = {
        name.removeprefix(root + "/")
        for name in expected
        if name not in {f"{root}/PKG-INFO", f"{root}/setup.cfg"}
    }
    if len(listed) != len(set(listed)):
        fail(
            "archive", "RCP4004", coordinate, "sdist SOURCES.txt has duplicate entries"
        )
    _check_names(set(listed), declared, coordinate)


def _check_source_tree(root: Path, expected: dict[str, str], coordinate: str) -> None:
    if root.is_symlink() or not root.is_dir():
        fail(
            "archive",
            "RCP4001",
            coordinate,
            "generated package source tree is unavailable",
        )
    found: dict[str, bytes] = {}
    for directory, subdirectories, filenames in os.walk(root, followlinks=False):
        for name in subdirectories + filenames:
            path = Path(directory) / name
            if path.is_symlink():
                fail(
                    "archive",
                    "RCP4001",
                    coordinate,
                    f"generated package tree contains a symbolic link: {path.relative_to(root).as_posix()!r}",
                )
        for name in filenames:
            path = Path(directory) / name
            relative = path.relative_to(root).as_posix()
            if not path.is_file():
                fail(
                    "archive",
                    "RCP4001",
                    coordinate,
                    f"generated package tree contains a non-file: {relative!r}",
                )
            try:
                found[relative] = path.read_bytes()
            except OSError:
                fail(
                    "archive",
                    "RCP4001",
                    coordinate,
                    f"generated package file cannot be read: {relative!r}",
                )
    _check_names(set(found), set(expected), coordinate)
    for name, content in expected.items():
        if found[name] != content.encode("utf-8"):
            fail(
                "archive",
                "RCP4001",
                coordinate,
                f"generated package file differs: {name!r}",
            )


def _check_toolchain(python: Path, lock: dict[str, Any], coordinate: str) -> None:
    script = (
        "import importlib.metadata as m, json, platform, sys; "
        "print(json.dumps({'python': platform.python_version(), "
        "'venv': sys.prefix != sys.base_prefix, "
        "'tools': {name: m.version(name) for name in "
        "('pip','setuptools','build','wheel','packaging','pyproject_hooks')}}))"
    )
    try:
        result = subprocess.run(
            (str(python), "-c", script), check=True, capture_output=True, text=True
        )
        actual = json.loads(result.stdout)
    except (OSError, subprocess.CalledProcessError, ValueError, KeyError):
        fail(
            "archive",
            "RCP4002",
            coordinate,
            "cannot inspect isolated Python build toolchain",
        )
    configured = lock["python"]
    if not actual["venv"] or tuple(
        int(part) for part in actual["python"].split(".")
    ) < (3, 11):
        fail(
            "archive",
            "RCP4002",
            coordinate,
            "build interpreter must be isolated Python 3.11 or newer",
        )
    if actual["python"] != configured["interpreterVersion"]:
        fail(
            "archive",
            "RCP4002",
            coordinate,
            f"build interpreter {actual['python']} differs from pin {configured['interpreterVersion']}",
        )
    for name in _BUILD_TOOLS:
        if actual["tools"].get(name) != configured["tools"].get(name):
            fail(
                "archive",
                "RCP4002",
                coordinate,
                f"build tool {name!r} differs from toolchain lock",
            )


def _canonical_wheel(source: Path, destination: Path) -> None:
    with (
        zipfile.ZipFile(source) as original,
        zipfile.ZipFile(destination, "w") as output,
    ):
        for name in sorted(original.namelist()):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = (stat.S_IFREG | 0o644) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            output.writestr(
                info,
                original.read(name),
                compress_type=zipfile.ZIP_DEFLATED,
                compresslevel=9,
            )


def _canonical_sdist(source: Path, destination: Path) -> None:
    with (
        tarfile.open(source, "r:gz") as original,
        destination.open("wb") as stream,
        gzip.GzipFile(
            fileobj=stream, mode="wb", filename="", mtime=ARCHIVE_EPOCH, compresslevel=9
        ) as compressed,
        tarfile.open(fileobj=compressed, mode="w", format=tarfile.PAX_FORMAT) as output,
    ):
        for member in sorted(original.getmembers(), key=lambda item: item.name):
            info = tarfile.TarInfo(member.name)
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            info.mtime = ARCHIVE_EPOCH
            info.mode = 0o755 if member.isdir() else 0o644
            if member.isdir():
                info.type = tarfile.DIRTYPE
                output.addfile(info)
            else:
                content = original.extractfile(member)
                assert content is not None
                data = content.read()
                info.size = len(data)
                output.addfile(info, io.BytesIO(data))


def build_archives(
    plan: EmissionPlan,
    model: dict[str, Any],
    source_tree: str | Path,
    output_directory: str | Path,
    build_python: str | Path,
    toolchain_lock: dict[str, Any],
    *,
    assembled: bool = False,
) -> ArchiveArtifacts:
    """Build, allowlist, and canonicalize one wheel and sdist from a clean copy."""
    coordinate = plan.target.package_key
    expected = render_package(plan, model)
    source = Path(source_tree)
    if assembled:
        expected = _assembled_source(plan, model, source)
    _check_source_tree(source, expected, coordinate)
    _check_toolchain(Path(build_python), toolchain_lock, coordinate)
    output = Path(output_directory)
    try:
        occupied = output.is_symlink() or (
            output.exists() and (not output.is_dir() or any(output.iterdir()))
        )
    except OSError:
        fail(
            "archive", "RCP4005", coordinate, "cannot inspect archive output directory"
        )
    if occupied:
        fail(
            "archive",
            "RCP4005",
            coordinate,
            "archive output directory must be new or empty",
        )
    wheel_name, sdist_name, _ = _artifact_names(plan)
    with TemporaryDirectory(prefix="rc-python-build-") as temporary:
        staging = Path(temporary) / "package"
        raw = Path(temporary) / "dist"
        try:
            shutil.copytree(source, staging)
        except OSError:
            fail(
                "archive",
                "RCP4001",
                coordinate,
                "cannot stage generated package source tree",
            )
        raw.mkdir()
        environment = os.environ.copy()
        environment.update(
            {
                "SOURCE_DATE_EPOCH": str(ARCHIVE_EPOCH),
                "PYTHONHASHSEED": "0",
                "PYTHONNOUSERSITE": "1",
                "PYTHONDONTWRITEBYTECODE": "1",
                "PYTHONUTF8": "1",
                "TZ": "UTC",
                "LC_ALL": "C",
            }
        )
        try:
            subprocess.run(
                (
                    str(build_python),
                    "-m",
                    "build",
                    "--no-isolation",
                    "--outdir",
                    str(raw),
                    str(staging),
                ),
                check=True,
                capture_output=True,
                text=True,
                env=environment,
            )
        except (OSError, subprocess.CalledProcessError):
            fail("archive", "RCP4003", coordinate, "pinned Python package build failed")
        _check_names(
            {path.name for path in raw.iterdir()}, {wheel_name, sdist_name}, coordinate
        )
        verify_wheel(raw / wheel_name, plan, model, expected)
        verify_sdist(raw / sdist_name, plan, model, expected)
        try:
            output.mkdir(parents=True, exist_ok=True)
            wheel = output / wheel_name
            sdist = output / sdist_name
            _canonical_wheel(raw / wheel_name, wheel)
            _canonical_sdist(raw / sdist_name, sdist)
        except OSError:
            fail(
                "archive",
                "RCP4005",
                coordinate,
                "cannot write canonical package archives",
            )
    verify_wheel(wheel, plan, model, expected)
    verify_sdist(sdist, plan, model, expected)
    return ArchiveArtifacts(wheel, sdist)


def _assembled_source(
    plan: EmissionPlan, model: dict[str, Any], root: Path
) -> dict[str, str]:
    """Allow only emitter source, native metadata, and declared assembly resources."""
    import yaml

    manifest_path = root / "runtimeconditions.file-manifest.yaml"
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if (
        set(manifest) != {"apiVersion", "kind", "files"}
        or manifest["apiVersion"] != "runtimeconditions.io/file-manifest/v1alpha1"
        or manifest["kind"] != "RuntimeConditionsFileManifest"
    ):
        raise ValueError("invalid generated file manifest")
    expected = render_package(plan, model)
    expected.update(render_assembly_metadata())
    prefix = f"src/{plan.target.import_package}/"
    resources = {
        prefix + name
        for name in (
            "runtimeconditions.binding-model.yaml",
            "runtimeconditions.extension.yaml",
            "runtimeconditions.binding-release.yaml",
        )
    }
    found: dict[str, str] = {}
    for name, digest in manifest["files"].items():
        path = Path(name)
        if (
            path.is_absolute()
            or ".." in path.parts
            or "\\" in name
            or path.as_posix() != name
        ):
            raise ValueError("unsafe generated file manifest path")
        if name not in expected and name not in resources:
            raise ValueError(f"undeclared assembled package file: {name}")
        content = (root / path).read_bytes()
        if sha256(content).hexdigest() != digest:
            raise ValueError(f"generated file digest differs: {name}")
        found[name] = content.decode("utf-8")
    if not set(expected) | resources <= set(found):
        raise ValueError("assembled package is missing required files")
    for name, expected_content in expected.items():
        if found[name] != expected_content:
            raise ValueError(f"emitter-owned source differs: {name}")
    found[manifest_path.name] = manifest_path.read_text(encoding="utf-8")
    return found
