"""Deterministic Python distribution metadata and binding resources."""

from __future__ import annotations

import json
import re
from typing import Any, cast

import yaml

from .emitter import EmissionPlan, TypeExpr
from .package import SHA_PATTERN, VERSION_PATTERN, fail

EMITTER_NAME = "runtimeconditions-binding-emitter"
EMITTER_VERSION = "0.1.0"
# Keep this equal to python.tools.setuptools in the shared toolchain lock.
SETUPTOOLS_VERSION = "84.0.0"


def _version(value: str, coordinate: str) -> str:
    match = VERSION_PATTERN.fullmatch(value)
    if match is None:
        fail(
            "package-config",
            "RCP1006",
            coordinate,
            f"unsupported package version {value!r}",
            "/version",
        )
    stable = ".".join(match.group(index) for index in (1, 2, 3))
    if match.group(4) is None:
        return stable
    prerelease = re.search(r"-(alpha|beta|rc)\.", value)
    assert prerelease is not None
    prefix = {"alpha": "a", "beta": "b", "rc": "rc"}[prerelease.group(1)]
    return f"{stable}{prefix}{match.group(4)}"


def _dependency_interval(value: str, coordinate: str) -> str:
    tested = _version(value, coordinate)
    major, minor, _ = (int(part) for part in value.split("-", 1)[0].split("."))
    next_breaking = f"0.{minor + 1}.0" if major == 0 else f"{major + 1}.0.0"
    return f">={tested},<{next_breaking}"


def _header(model: dict[str, Any]) -> str:
    return (
        f"# Code generated by {EMITTER_NAME} {EMITTER_VERSION} "
        f"from model {model['metadata']['semanticSha256']}; DO NOT EDIT.\n"
    )


def _pyproject(plan: EmissionPlan, model: dict[str, Any]) -> str:
    target = plan.target
    dependencies = sorted(
        target.dependencies, key=lambda item: (item.distribution_name, item.extension)
    )
    names = [item.distribution_name for item in dependencies]
    if len(names) != len(set(names)):
        fail(
            "package-config",
            "RCP1006",
            target.package_key,
            "multiple direct extensions use the same Python distribution name",
            "/dependencies",
        )
    lines = [
        _header(model).rstrip("\n"),
        "[build-system]",
        f'requires = ["setuptools=={SETUPTOOLS_VERSION}"]',
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        f"name = {json.dumps(target.distribution_name)}",
        f"version = {json.dumps(_version(target.version, target.package_key))}",
        f'requires-python = ">={target.minimum_python_version}"',
        "dependencies = [",
    ]
    for dependency in dependencies:
        interval = _dependency_interval(dependency.version, dependency.extension)
        lines.append(f"    {json.dumps(dependency.distribution_name + interval)},")
    lines.extend(
        (
            "]",
            "",
            "[project.urls]",
            f"Repository = {json.dumps(target.repository_url)}",
            "",
            "[tool.setuptools.packages.find]",
            'where = ["src"]',
            f"include = [{json.dumps(target.import_package)}, {json.dumps(target.import_package + '.*')}]",
            "",
            "[tool.setuptools.package-data]",
            f'{json.dumps(target.import_package)} = ["py.typed", "runtimeconditions.bindings.yaml", "runtimeconditions.binding-model.yaml", "runtimeconditions.extension.yaml", "runtimeconditions.binding-release.yaml"]',
            "",
        )
    )
    return "\n".join(lines)


def _location(provenance: dict[str, Any]) -> str:
    return cast(str, provenance["coordinate"] + provenance.get("jsonPointer", ""))


def _model_ref(provenance: dict[str, Any]) -> dict[str, str]:
    result = {"coordinate": provenance["coordinate"]}
    if pointer := provenance.get("jsonPointer"):
        result["jsonPointer"] = pointer
    return result


def _model_locations(
    model: dict[str, Any],
) -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]]]:
    provenances: dict[str, dict[str, Any]] = {}
    shapes: dict[str, dict[str, Any]] = {}

    def add(item: dict[str, Any]) -> None:
        provenance = item["provenance"]
        location = _location(provenance)
        previous = provenances.get(location)
        if previous is not None and previous != provenance:
            fail(
                "model",
                "RCP1012",
                location,
                "ambiguous legacy plan coordinate; separate model coordinate and JSON Pointer are required",
            )
        provenances[location] = provenance

    def walk(shape: dict[str, Any]) -> None:
        add(shape)
        shapes.setdefault(_location(shape["provenance"]), shape)
        for property_ in shape.get("properties", []):
            add(property_)
            walk(property_["shape"])
        for child in (shape.get("items"), shape.get("mapValues")):
            if child is not None:
                walk(child)
        for child in shape.get("variants", []):
            walk(child)

    vocabulary = model["vocabulary"]
    for group in (
        "ownedDeclarations",
        "importedDeclarations",
        "interfaces",
        "conditionFields",
        "valueDomains",
    ):
        for item in vocabulary.get(group, []):
            add(item)
    # Scope projections combine all applicable schemas. Prefer these complete
    # shapes when one schema supplies fields and another adds constraints.
    for scope in model.get("scopes", []):
        if projection := scope.get("projection"):
            walk(projection)
    for schema in model.get("schemas", []):
        add(schema)
        walk(schema["projection"])
        for definition in schema.get("definitions", []):
            add(definition)
            walk(definition["shape"])
    return provenances, shapes


def _reference(expression: TypeExpr, plan: EmissionPlan) -> dict[str, Any]:
    if expression.kind in {"object", "enum", "ref", "alias"}:
        return {"type": plan.names[expression.symbol_key]}
    builtin = {
        "string": "str",
        "boolean": "bool",
        "integer": "int",
        "number": "float",
        "null": "None",
        "any": "JSONValue",
    }
    return {"builtin": builtin[expression.kind]}


def _structural_types(
    plan: EmissionPlan,
    provenances: dict[str, dict[str, Any]],
    shapes: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    contracts = {item.method: item.coordinate for item in plan.declarations}
    contracts.update(
        {item.method: item.coordinate for item in plan.imported_declarations}
    )
    result: list[dict[str, Any]] = []
    for item in plan.types:
        shape = shapes[item.coordinate]
        alias_kind = item.expression.kind if item.expression is not None else ""
        construct = (
            "wrapper"
            if item.kind == "object" and shape["kind"] != "object"
            else "object"
            if item.kind == "object"
            else "scalar"
            if item.kind == "enum"
            else {"array": "collection", "map": "map", "union": "union"}[alias_kind]
        )
        entry: dict[str, Any] = {
            "modelRef": _model_ref(provenances[item.coordinate]),
            "sourceName": item.source_name,
            "nativeName": item.name,
            "construct": construct,
            "file": "bindings.py",
        }
        if item.kind == "enum":
            entry["underlying"] = "str"
            entry["members"] = [
                {
                    "modelRef": _model_ref(provenances[item.coordinate]),
                    "nativeName": native,
                    "value": value,
                }
                for native, value in item.members
            ]
        if item.kind == "object":
            fields: list[dict[str, Any]] = []
            for field in item.fields:
                value = _reference(field.type_expr, plan)
                if field.default_none:
                    value["nullable"] = True
                fields.append(
                    {
                        "modelRef": _model_ref(provenances[field.coordinate]),
                        "sourceName": item.source_name
                        if construct == "wrapper"
                        else field.source_name,
                        "nativeName": field.name,
                        "required": field.required,
                        "value": value,
                        **({"synthetic": True} if construct == "wrapper" else {}),
                    }
                )
            entry["fields"] = fields
            if item.marker is not None:
                entry["implements"] = [
                    {
                        "declarationCoordinate": contracts[item.marker.method],
                        "markerMethod": item.marker.method,
                    }
                ]
        if item.kind == "alias":
            assert item.expression is not None
            if construct in {"collection", "map"}:
                child = shape["items" if construct == "collection" else "mapValues"]
                entry["element"] = {
                    "modelRef": _model_ref(child["provenance"]),
                    "value": _reference(item.expression.arguments[0], plan),
                }
            else:
                entry["variants"] = [
                    {
                        "modelRef": _model_ref(child["provenance"]),
                        "value": _reference(expression, plan),
                    }
                    for child, expression in zip(
                        shape["variants"], item.expression.arguments, strict=True
                    )
                ]
        result.append(entry)
    return sorted(result, key=lambda entry: entry["nativeName"])


def _manifest(plan: EmissionPlan, model: dict[str, Any]) -> str:
    provenances, shapes = _model_locations(model)
    declarations = {
        item["kind"]: item
        for group in ("ownedDeclarations", "importedDeclarations")
        for item in model["vocabulary"].get(group, [])
    }
    fields = {
        (item["kind"], item.get("interfaceType", ""), item["path"]): item
        for item in model["vocabulary"].get("conditionFields", [])
        if item["owner"] == model["rootExtension"]["id"]
    }
    root_bindings: list[dict[str, Any]] = []
    for schema in model.get("schemas", []):
        if schema["owner"] != model["rootExtension"]["id"]:
            continue
        kind = schema.get("kind", schema["id"])
        if kind not in declarations:
            continue
        interface_type = schema.get("interfaceType", "")
        for property_ in schema["projection"].get("properties", []):
            name = property_["name"]
            source_name = (
                interface_type if name == "interface" and interface_type else name
            )
            # Source names and referenced shapes need not identify a unique property.
            native_name = plan.names.get(f"type:field:{schema['coordinate']}:{name}")
            if native_name is None:
                fail(
                    "model",
                    "RCP1012",
                    schema["coordinate"],
                    f"root property {name!r} has no declaration field type",
                )
            vocabulary_field = fields.get((kind, interface_type, name))
            role = (
                "interface"
                if name == "interface" and interface_type
                else "condition-field"
                if vocabulary_field is not None
                else "schema-field"
            )
            binding: dict[str, Any] = {
                "role": role,
                "modelRef": _model_ref(property_["provenance"]),
                "declarationCoordinate": declarations[kind]["coordinate"],
                "scope": {"kind": kind},
                "sourceName": source_name,
                "path": [{"name": name}],
                "value": {"type": native_name},
                "schemaCoordinate": schema["coordinate"],
            }
            if interface_type:
                binding["scope"]["interfaceType"] = interface_type
            if role == "interface":
                binding["fixedInterfaceType"] = interface_type
            if vocabulary_field is not None:
                binding["vocabularyCoordinate"] = vocabulary_field["coordinate"]
            root_bindings.append(binding)

    document = {
        "apiVersion": "runtimeconditions.io/bindings/v1alpha2",
        "kind": "RuntimeConditionsBindingManifest",
        "generated": {
            "nonEditable": True,
            "emitter": f"{EMITTER_NAME}@sha256:{plan.target.emitter_sha256}",
            "version": EMITTER_VERSION,
        },
        "model": {
            "apiVersion": model["apiVersion"],
            "semanticSha256": plan.model_digest,
        },
        "extension": {
            "id": model["rootExtension"]["id"],
            "semanticSha256": model["rootExtension"]["semanticSha256"],
        },
        "package": {
            "language": "python",
            "coordinate": plan.target.distribution_name,
            "name": plan.target.import_package,
            "version": _version(plan.target.version, plan.target.package_key),
            "minimumPythonVersion": plan.target.minimum_python_version,
        },
        "declarations": [
            {
                "modelRef": _model_ref(provenances[item.coordinate]),
                "owner": model["rootExtension"]["id"],
                "sourceName": item.kind,
                "function": item.function,
                "markerInterface": item.protocol,
                "markerMethod": item.method,
                "file": "bindings.py",
            }
            for item in plan.declarations
        ],
        "importedMarkerContracts": [
            {
                "modelRef": _model_ref(provenances[item.coordinate]),
                "owner": item.owner,
                "sourceName": item.kind,
                "markerInterface": item.protocol,
                "markerMethod": item.method,
                "providerPackage": item.provider_import,
            }
            for item in plan.imported_declarations
        ],
        "rootBindings": sorted(
            root_bindings,
            key=lambda item: (
                item["declarationCoordinate"],
                item["modelRef"]["coordinate"],
                item["modelRef"].get("jsonPointer", ""),
            ),
        ),
        "types": _structural_types(plan, provenances, shapes),
    }
    return _header(model) + yaml.safe_dump(
        document, sort_keys=False, allow_unicode=True, default_flow_style=False
    )


def render_resources(plan: EmissionPlan, model: dict[str, Any]) -> dict[str, str]:
    """Render package metadata and resources without writing an output tree."""
    if not isinstance(plan.target.emitter_sha256, str) or not SHA_PATTERN.fullmatch(
        plan.target.emitter_sha256
    ):
        fail(
            "package-config",
            "RCP1006",
            plan.target.package_key,
            "emitterSha256 must be a 64-character lowercase SHA-256 of the emitter tool",
            "/emitterSha256",
        )
    if (
        model["metadata"]["semanticSha256"] != plan.model_digest
        or model["rootExtension"]["id"] != plan.target.root_extension
    ):
        fail("model", "RCP1003", "model", "emission plan does not match supplied model")
    root = model["rootExtension"]
    closure_roots = [item for item in model["extensions"] if item["id"] == root["id"]]
    if len(closure_roots) != 1 or (
        closure_roots[0]["semanticSha256"] != root["semanticSha256"]
    ):
        fail(
            "model",
            "RCP1003",
            root["id"],
            "root extension digest does not match model extension closure",
        )
    prefix = f"src/{plan.target.import_package}"
    return {
        "pyproject.toml": _pyproject(plan, model),
        f"{prefix}/py.typed": "",
        f"{prefix}/runtimeconditions.bindings.yaml": _manifest(plan, model),
    }
