"""Deterministic Python API and inert conformance-source rendering."""

from __future__ import annotations

import ast
import json
import shutil
import subprocess
import sys
from collections import defaultdict
from importlib import metadata
from pathlib import Path
from typing import Any

from .emitter import EmissionPlan, TypeExpr, TypePlan
from .metadata import EMITTER_NAME, EMITTER_VERSION, render_resources
from .package import fail


def _header(model: dict[str, Any]) -> str:
    digest = model["metadata"]["semanticSha256"]
    return (
        f"# Code generated by {EMITTER_NAME} {EMITTER_VERSION} "
        f"from model {digest}; DO NOT EDIT.\n"
    )


def _exports(plan: EmissionPlan) -> list[str]:
    names = {"Declaration"} if plan.declarations else set()
    names.update(item.name for item in plan.types)
    for declaration in plan.declarations:
        names.update((declaration.function, declaration.protocol))
    for imported_declaration in plan.imported_declarations:
        names.update((imported_declaration.function, imported_declaration.protocol))
    if plan.uses_json_value:
        names.add("JSONValue")
    return sorted(names)


def _all_literal(names: list[str]) -> list[str]:
    return [
        "__all__ = [",
        *(f"    {json.dumps(name, ensure_ascii=False)}," for name in names),
        "]",
    ]


def _bindings_source(plan: EmissionPlan, model: dict[str, Any]) -> str:
    lines = [
        _header(model).rstrip("\n"),
        "from __future__ import annotations",
        "",
    ]
    if plan.declarations or any(item.kind == "object" for item in plan.types):
        lines.append("from dataclasses import dataclass")
    if any(item.kind == "enum" for item in plan.types):
        lines.append("from enum import StrEnum")
    typing_imports: list[str] = []
    if plan.declarations:
        typing_imports.append("Protocol")
    if plan.uses_json_value or any(
        "Sequence[" in item.annotation for item in plan.types if item.kind == "alias"
    ):
        typing_imports.append("Sequence")
    if plan.uses_json_value or any(item.kind == "alias" for item in plan.types):
        typing_imports.append("TypeAlias")
    if typing_imports:
        lines.append(f"from typing import {', '.join(typing_imports)}")
    imports: dict[str, set[str]] = defaultdict(set)
    for imported_declaration in plan.imported_declarations:
        if imported_declaration.provider_import is None:
            fail(
                "model",
                "RCP1011",
                imported_declaration.coordinate,
                "imported declaration has no direct dependency provider",
            )
        imports[imported_declaration.provider_import].update(
            (imported_declaration.function, imported_declaration.protocol)
        )
    if imports:
        lines.append("")
        for provider in sorted(imports):
            lines.append(
                f"from {provider} import {', '.join(sorted(imports[provider]))}"
            )

    if plan.declarations:
        lines.extend(
            (
                "",
                "",
                "@dataclass(frozen=True, kw_only=True)",
                "class Declaration:",
                "    pass",
            )
        )
    for owned_declaration in sorted(plan.declarations, key=lambda item: item.protocol):
        lines.extend(
            (
                "",
                "",
                f"class {owned_declaration.protocol}(Protocol):",
                f"    def {owned_declaration.method}(self) -> None: ...",
            )
        )
    if plan.uses_json_value:
        lines.extend(("", "", f"JSONValue: TypeAlias = {plan.json_value_alias_rhs}"))

    for type_plan in sorted(plan.types, key=lambda item: item.name):
        lines.extend(("", ""))
        if type_plan.kind == "enum":
            lines.append(f"class {type_plan.name}(StrEnum):")
            lines.extend(
                f"    {name} = {json.dumps(value, ensure_ascii=False)}"
                for name, value in type_plan.members
            )
        elif type_plan.kind == "alias":
            lines.append(f"{type_plan.name}: TypeAlias = {type_plan.alias_rhs}")
        elif type_plan.kind == "object":
            lines.extend(
                ("@dataclass(frozen=True, kw_only=True)", f"class {type_plan.name}:")
            )
            for field in type_plan.fields:
                default = " = None" if field.default_none else ""
                lines.append(f"    {field.name}: {field.annotation}{default}")
            if type_plan.marker:
                if type_plan.fields:
                    lines.append("")
                lines.extend(
                    (
                        f"    def {type_plan.marker.method}(self) -> None:",
                        "        return None",
                    )
                )
            elif not type_plan.fields:
                lines.append("    pass")
        else:
            raise AssertionError(f"unplanned type kind {type_plan.kind}")

    for owned_declaration in sorted(plan.declarations, key=lambda item: item.function):
        lines.extend(
            (
                "",
                "",
                f"def {owned_declaration.function}(*fields: {owned_declaration.protocol}) -> Declaration:",
                "    return Declaration()",
            )
        )
    lines.extend(("", "", *_all_literal(_exports(plan)), ""))
    return "\n".join(lines)


def _init_source(plan: EmissionPlan, model: dict[str, Any]) -> str:
    exports = _exports(plan)
    lines = [
        _header(model).rstrip("\n"),
        "from __future__ import annotations",
        "",
        "from .bindings import (",
    ]
    lines.extend(f"    {name}," for name in exports)
    lines.extend((")", "", *_all_literal(exports), ""))
    return "\n".join(lines)


def _sample(
    expr: TypeExpr,
    plan: EmissionPlan,
    types: dict[str, TypePlan],
    active: tuple[str, ...] = (),
    selected_optional: str | None = None,
) -> str:
    if expr.kind == "string":
        return '"sample"'
    if expr.kind == "boolean":
        return "True"
    if expr.kind == "integer":
        return "1"
    if expr.kind == "number":
        return "1.0"
    if expr.kind == "null":
        return "None"
    if expr.kind == "any":
        return '"sample"'
    if expr.kind == "array":
        return f"({_sample(expr.arguments[0], plan, types, active)},)"
    if expr.kind == "map":
        return '{"sample": ' + _sample(expr.arguments[0], plan, types, active) + "}"
    if expr.kind == "union":
        return _sample(expr.arguments[0], plan, types, active)
    name = plan.names[expr.symbol_key]
    type_plan = types[name]
    if type_plan.kind == "enum":
        return f"b.{name}.{type_plan.members[0][0]}"
    if type_plan.kind == "alias":
        if name in active:
            fail(
                "model",
                "RCP1012",
                type_plan.coordinate,
                "recursive alias has no finite conformance sample",
            )
        assert type_plan.expression is not None
        return _sample(type_plan.expression, plan, types, active + (name,))
    if type_plan.kind == "object":
        repeated = name in active
        optional_fields = [
            field.name for field in type_plan.fields if field.default_none
        ]
        if selected_optional is None and optional_fields:
            selected_optional = optional_fields[0]
        arguments: list[str] = []
        for field in type_plan.fields:
            if field.default_none and (repeated or field.name != selected_optional):
                value = "None"
            elif (
                repeated
                and not field.default_none
                and field.type_expr.kind in {"object", "ref", "alias"}
            ):
                fail(
                    "model",
                    "RCP1012",
                    field.coordinate,
                    "required recursive field has no finite conformance sample",
                )
            else:
                value = _sample(field.type_expr, plan, types, active + (name,))
            arguments.append(f"{field.name}={value}")
        return f"b.{name}({', '.join(arguments)})"
    raise AssertionError(f"unplanned type kind {type_plan.kind}")


def _field_groups(fields: list[TypePlan]) -> list[list[TypePlan]]:
    groups: dict[str, list[TypePlan]] = defaultdict(list)
    for field in fields:
        groups[field.schema_coordinate].append(field)
    return [
        sorted(groups[key], key=lambda item: item.name) for key in sorted(groups)
    ] or [[]]


def _conformance_source(plan: EmissionPlan, model: dict[str, Any]) -> str:
    lines = [
        _header(model).rstrip("\n"),
        "from __future__ import annotations",
        "",
        "from . import bindings as b",
        "",
        "",
        "def exercise() -> None:",
    ]
    if plan.uses_json_value:
        lines.extend(
            (
                '    _json_scalar: b.JSONValue = "sample"',
                '    _json_array: b.JSONValue = ("sample",)',
                '    _json_map: b.JSONValue = {"sample": "sample"}',
            )
        )
    types = {item.name: item for item in plan.types}
    object_variables: dict[str, str] = {}
    alternate_objects: dict[str, list[str]] = defaultdict(list)
    for index, type_plan in enumerate(sorted(plan.types, key=lambda item: item.name)):
        if type_plan.kind == "enum":
            for member_index, (member, _) in enumerate(type_plan.members):
                lines.append(
                    f"    _enum_{index}_{member_index}: b.{type_plan.name} = "
                    f"b.{type_plan.name}.{member}"
                )
        elif type_plan.kind == "alias":
            assert type_plan.expression is not None
            sample = _sample(type_plan.expression, plan, types)
            lines.append(f"    _alias_{index}: b.{type_plan.name} = {sample}")
            if type_plan.expression.kind == "union":
                for variant_index, variant in enumerate(type_plan.expression.arguments):
                    sample = _sample(variant, plan, types)
                    lines.append(
                        f"    _variant_{index}_{variant_index}: b.{type_plan.name} = {sample}"
                    )
        else:
            object_expr = TypeExpr(
                "object",
                symbol_key=next(
                    key
                    for key, value in plan.names.items()
                    if value == type_plan.name and key.startswith("type:")
                ),
            )
            sample = _sample(object_expr, plan, types)
            variable = f"_object_{index}"
            object_variables[type_plan.name] = variable
            lines.append(f"    {variable}: b.{type_plan.name} = {sample}")
            optional_fields = [
                field.name for field in type_plan.fields if field.default_none
            ]
            for optional_index, optional_name in enumerate(
                optional_fields[1:], start=1
            ):
                sample = _sample(
                    object_expr, plan, types, selected_optional=optional_name
                )
                alternate = f"_object_optional_{index}_{optional_index}"
                alternate_objects[type_plan.name].append(alternate)
                lines.append(f"    {alternate}: b.{type_plan.name} = {sample}")

    declaration_index = 0
    for declaration in sorted(plan.declarations, key=lambda item: item.function):
        fields = [
            item
            for item in plan.types
            if item.is_declaration_field
            and item.marker
            and item.marker.owner == plan.target.root_extension
            and item.marker.protocol == declaration.protocol
        ]
        if not fields:
            # A declaration-only package cannot invent an interface supplied
            # by a consumer's other installed dependency. Consumer fixtures
            # provide complete calls; retain native API coverage here.
            lines.append(
                f"    _deferred_declaration_{declaration.function} = "
                f"b.{declaration.function}"
            )
            continue
        for ordered in _field_groups(fields):
            arguments = ", ".join(object_variables[item.name] for item in ordered)
            lines.append(
                f"    _declaration_{declaration_index}: b.Declaration = "
                f"b.{declaration.function}({arguments})"
            )
            declaration_index += 1
            for item in ordered:
                for alternate in alternate_objects[item.name]:
                    alternative_arguments = ", ".join(
                        alternate
                        if field.name == item.name
                        else object_variables[field.name]
                        for field in ordered
                    )
                    lines.append(
                        f"    _declaration_{declaration_index}: b.Declaration = "
                        f"b.{declaration.function}({alternative_arguments})"
                    )
                    declaration_index += 1
    imported_index = 0
    for imported_declaration in sorted(
        plan.imported_declarations, key=lambda item: item.function
    ):
        fields = [
            item
            for item in plan.types
            if item.is_declaration_field
            and item.marker
            and item.marker.owner == imported_declaration.owner
        ]
        if not fields:
            lines.append(
                f"    _deferred_imported_{imported_index} = "
                f"b.{imported_declaration.function}"
            )
            imported_index += 1
            continue
        for ordered in _field_groups(fields):
            arguments = ", ".join(object_variables[item.name] for item in ordered)
            lines.append(
                f"    _imported_{imported_index} = "
                f"b.{imported_declaration.function}({arguments})"
            )
            imported_index += 1
    if len(lines) == 7:
        lines.append("    pass")
    lines.append("")
    return "\n".join(lines)


def render_sources(plan: EmissionPlan, model: dict[str, Any]) -> dict[str, str]:
    """Render production API source; synthetic exercises belong to tooling tests."""
    if (
        model["metadata"]["semanticSha256"] != plan.model_digest
        or model["rootExtension"]["id"] != plan.target.root_extension
    ):
        fail("model", "RCP1003", "model", "emission plan does not match supplied model")
    prefix = f"src/{plan.target.import_package}"
    sources = {
        f"{prefix}/__init__.py": _init_source(plan, model),
        f"{prefix}/bindings.py": _bindings_source(plan, model),
    }
    try:
        formatter_version = metadata.version("ruff")
    except metadata.PackageNotFoundError:
        fail(
            "toolchain",
            "RCP4002",
            plan.target.package_key,
            "pinned Ruff formatter is unavailable",
        )
    if formatter_version != "0.16.9":
        fail(
            "toolchain",
            "RCP4002",
            plan.target.package_key,
            f"Ruff formatter version {formatter_version!r} differs from toolchain lock",
        )
    formatter = Path(sys.executable).with_name("ruff")
    if not formatter.is_file():
        resolved = shutil.which("ruff")
        if resolved is None:
            fail(
                "toolchain",
                "RCP4002",
                plan.target.package_key,
                "pinned Ruff formatter is unavailable",
            )
        formatter = Path(resolved)
    try:
        binary_version = subprocess.run(
            [str(formatter), "--version"], text=True, capture_output=True, check=True
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        fail(
            "toolchain",
            "RCP4002",
            plan.target.package_key,
            "pinned Ruff formatter failed",
        )
    if binary_version != f"ruff {formatter_version}":
        fail(
            "toolchain",
            "RCP4002",
            plan.target.package_key,
            f"Ruff executable {binary_version!r} differs from toolchain lock",
        )
    formatted: dict[str, str] = {}
    for path, source in sources.items():
        ast.parse(source, filename=path, feature_version=(3, 11))
        try:
            result = subprocess.run(
                [
                    str(formatter),
                    "format",
                    "--isolated",
                    "--target-version",
                    "py311",
                    "--stdin-filename",
                    Path(path).name,
                    "-",
                ],
                input=source,
                text=True,
                capture_output=True,
                check=True,
            )
        except (OSError, subprocess.CalledProcessError):
            fail(
                "toolchain",
                "RCP4002",
                plan.target.package_key,
                "pinned Ruff formatter failed",
            )
        formatted[path] = result.stdout
    return formatted


def emit_sources(
    plan: EmissionPlan, model: dict[str, Any], output_directory: str | Path
) -> tuple[str, ...]:
    """Write the three generated Python source files into a new or empty tree."""
    return _write_files(render_sources(plan, model), plan, output_directory)


def render_package(plan: EmissionPlan, model: dict[str, Any]) -> dict[str, str]:
    """Render the complete Phase 3 emitter-owned package tree in memory."""
    return {**render_sources(plan, model), **render_resources(plan, model)}


def emit_package(
    plan: EmissionPlan, model: dict[str, Any], output_directory: str | Path
) -> tuple[str, ...]:
    """Write API source, package metadata, and resources into a new tree."""
    return _write_files(render_package(plan, model), plan, output_directory)


def _write_files(
    files: dict[str, str], plan: EmissionPlan, output_directory: str | Path
) -> tuple[str, ...]:
    output = Path(output_directory)
    occupied = False
    try:
        occupied = output.is_symlink() or (
            output.exists() and (not output.is_dir() or any(output.iterdir()))
        )
    except OSError:
        fail(
            "output",
            "RCP3002",
            plan.target.package_key,
            "cannot inspect output directory",
        )
    if occupied:
        fail(
            "output",
            "RCP3001",
            plan.target.package_key,
            "output directory must be new or empty and not a symbolic link",
        )
    try:
        output.mkdir(parents=True, exist_ok=True)
        for relative_path in sorted(files):
            destination = output / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            with destination.open("x", encoding="utf-8", newline="\n") as stream:
                stream.write(files[relative_path])
    except FileExistsError:
        fail(
            "output",
            "RCP3001",
            plan.target.package_key,
            "output directory must be new or empty and not a symbolic link",
        )
    except OSError:
        fail(
            "output",
            "RCP3002",
            plan.target.package_key,
            "cannot write generated package files",
        )
    return tuple(sorted(files))


def render_assembly_metadata() -> dict[str, str]:
    """Native source-distribution inclusion rules for orchestrator-owned files."""
    return {"MANIFEST.in": "include runtimeconditions.file-manifest.yaml\n"}
